### ISSUE TITLE
java, etc.

### ISSUE THREAD

**Issue by czanik** [amitn322/blackesk#1]
First of all: thanks, tested blackesk, and it works great.

Checking the scripts, I see that syslog-ng/build.sh also adds Java support. It increases both to the build time and the size of the container considerably. And as the syslog-ng.conf shows, it is not used at all. It should be removed.

The syslog-ng.conf has many commented out parts. It makes a bit hard to read.

**Comment by amitn322** [comment]
@czanik  Thank you for trying it out. Until the previous versions java was required to be able to send to elasticsearch using the elasticsearch2 library and therefore java was part of the installation. Now that it is not being used, I will remove it from the script. Also clean up the syslog-ng.conf. 

Thank You,
Amit

**Comment by amitn322** [comment]
Thanks, I have updated the build script and the configuration file.
