### ISSUE TITLE
extras/loggen.sh logs to the host

### ISSUE THREAD

**Issue by czanik** [amitn322/blackesk#2]
I tried to find the 10 log messages generated during installation, but found only syslog-ng internal() messages. Taking a closer look at extras/loggen.sh I found, that:
```
logger -t sshd -f /tmp/ssh_logs.txt 
```
Which means, that logs are sent to the local syslog instead of the one just installed in Docker. The above command only works, if logs from localhost are forwarded to port 514 even before installation.
```
logger -T --rfc3164 -n 127.0.0.1 -P 514 -t sshd -f /tmp/ssh_logs.txt
```
The above variant should resolve this problem.

**Comment by amitn322** [comment]
Thanks a lot , I will update the script to send over to the syslog on 
docker. I did go back and check the script and looks like I am 
generating the logs only after all the build stuff is completed. The 
logs should still be in the Elasticsearch, may be some timing issue ? I 
had that timing issue when I had the VM that i run the dockers put on 
sleep at times. I will look into it tonight !

**Comment by amitn322** [comment]
@czanik I fixed this issue. The reason you weren't seeing the generated logs wasn't because syslog was sent to local, rather it was because of the timezone. Also the logger was running after the installation was complete. I did however, update to your style, I like that better. Thanks again !
