### ISSUE TITLE
calling loggen.sh from install.sh fails on Debian

### ISSUE THREAD

**Issue by czanik** [amitn322/blackesk#3]
When running install.sh on Debian, calling loggen.sh fails:
```
Generating Some Fake Logs, you can delete the index and start over..
./extras/loggen.sh: 13: ./extras/loggen.sh: arithmetic expression: expecting primary: "  % 65535 + 2000 "
```
The problem seems to be, that ```loggen.sh``` needs ```bash```, but sh on Debian is ```dash```. Replacing:
```
sh ./extras/loggen.sh 10
```
with
```
bash ./extras/loggen.sh 10
```
seems to solve the problem.

**Comment by amitn322** [comment]
@czanik , Fixed and pushed the code. Thank you for the help !
