### ISSUE TITLE
geopoint mapping

### ISSUE THREAD

**Issue by czanik** [amitn322/blackesk#4]
I tried to use mapping below, so that ```geopoint``` could be shown on a map, but it did not work. As it was the first time I used Elastic 7.8 also first time using access control, I'm not sure the the problem is. It would be nice to have mapping working out of box for geopoint.
```
PUT syslog-ng
{
   "mappings" : {
         "properties" : {
            "geopoint" : {
                "type" : "geo_point"
            }
         }
   }
}
```

**Comment by amitn322** [comment]
@czanik , I have updated the installer to take care of this. Thank's a lot for bringing this up. I appreciate your help.
