### ISSUE TITLE
install sh error.

### ISSUE THREAD

**Issue by owarz** [amitn322/blackesk#5]
install.sh: 70: Syntax error: "(" unexpected

os:ubuntu serv 20

**Comment by amitn322** [comment]
can you put this in a file `test.sh` and run `sh test.sh` ? Let me know what output you get. I will try to run on an ubuntu server tonight. 


```bash
#!/bin/bash
function testFunction()
{
  echo "This is test function" 
}

testFunction
```

**Comment by owarz** [comment]
hello,

test.sh: 2: test.sh: Syntax error: "(" unexpected

**Comment by amitn322** [comment]
Can you please run the installer script as below : 

```bash
bash install.sh
```
That should fix it. Apparently sh doesn't interpret the function.

**Comment by owarz** [comment]
thanks, i haven't tried this.
I apologize for bothering you with such a simple thing.

**Comment by amitn322** [comment]
No problem, Just didn't have an ubuntu machine to test.
