### ISSUE TITLE
Error related to Syslog during install install - Cent OS 8

### ISSUE THREAD

**Issue by bamit99** [amitn322/blackesk#8]
Getting the following error. Installing the same on Cent OS 8. Should I try a different version. I am attaching a screenshot too.

mkdir -p modules/java/syslog-ng-core/classes
  GEN      modules/java/syslog-ng-core/classes/org/syslog_ng/LogMessage.class
/bin/sh: /tmp/syslog-ng-3.34.1/: Permission denied
![Capture](https://user-images.githubusercontent.com/32737966/135753293-623262c9-a636-4322-8ccc-988b8f3d9d28.PNG)

  GEN      modules/java/org_syslog_ng_LogMessage.h
make: *** [Makefile:28678: modules/java/org_syslog_ng_LogMessage.h] Error 126
ERROR: Service 'syslog-ng' failed to build: The command '/bin/sh -c /build.sh' returned a non-zero code: 2

**Comment by amitn322** [comment]
Sorry for the delay, are you trying the single node install or multinode ? Also do you have selinux enabled ? Try running with selinux disabled and if that works, I will update the code to work with Selinux enabled. 

Thank You,
Amit

**Comment by sarifern** [comment]
Hi Amit, I ran into the same issue. Disabled Selinux but it still fails:

``` 
mkdir -p modules/java/syslog-ng-core/classes
  GEN      modules/java/syslog-ng-core/classes/org/syslog_ng/LogMessage.class
  GEN      modules/java/org_syslog_ng_LogMessage.h
/bin/sh: /tmp/syslog-ng-3.34.1/: Permission denied
make: *** [Makefile:28678: modules/java/org_syslog_ng_LogMessage.h] Error 126
The command '/bin/sh -c /build.sh' returned a non-zero code: 2
ERROR: Service 'syslog-ng' failed to build : Build failed
Waiting for Elasticsearch to be ready...
^C
[root@sharkathon blackesk]# sestatus
SELinux status:                 disabled
```

**Comment by amitn322** [comment]
@bamit99 @sarifern This issue has been resolved. Please pull the latest code, try again and let me know if you encounter any issues.
