### ISSUE TITLE
Permission denied on syslog-ng build

### ISSUE THREAD

**Issue by vibrion121** [amitn322/blackesk#9]
Hi! im getting this error:
/bin/sh: /tmp/syslog-ng-3.34.1/: Permission denied
tryed different approcahes without success (tryed this approach too https://vsupalov.com/docker-shared-permissions/)
thanks Martin!

**Comment by amitn322** [comment]
Can you put some more messages around that error and or a screenshot ? That would help me figure out where in the cod eit is erroring out. 

Thank You,
Amit

**Comment by vibrion121** [comment]
This is more simple: https://asciinema.org/a/ZaB1rIsDSqnmZRAFiy8dpVLTd
;)
Thanks Martin

**Comment by benempson** [comment]
I'm getting the same... Thanks for your work, wishing I could try it out!

![2021-12-03_18-01-06](https://user-images.githubusercontent.com/1347803/144642878-7ca07332-c72b-4a8e-ac33-4e31dd3b822c.png)

**Comment by amitn322** [comment]
Hi @benempson sorry about the delay, what version of operating system are you using ? I can try it out and see if I can replicate the issue.

**Comment by benempson** [comment]
Hi there, I tried this on Synology DSM 7.

**Comment by 0xJs** [comment]
Got the same error on debian 11 and ubuntu 20.04

**Comment by 0xJs** [comment]
But there is nothing in the /tmp/ directory. No syslog-ng file.

**Comment by amitn322** [comment]
@0xJs  @benempson @vibrion121 apologies for the delay , but do you have the latest code ? Please try to pull the latest code from github and try to run again. That issue should have been caused by the Selinux being enabled on the system. I have since updated the nodes file to use Z flag. If that does not work , can you try disabling Selinux and see if that works ? YOu can then re-enable Selinux but just to check and make sure it's not related to that. 

Disable Selinux : 
```
setenforce 0
```
Enable Selinux: 
```
setenforce 1
```

**Comment by BosmanSander** [comment]
@amitn322 I've pulled the latest code from your Github, but I've still got permission issues.
I've given the /tmp/syslog folder all the permissions and changed ownership to root.

I also don't seem to have Selinux installed in either my docker container or my host that I run the docker on.
This is the error that I get when starting or installing the docker:

![error](https://user-images.githubusercontent.com/11984491/148201498-49fe8a85-3c47-42d7-a7d3-8071a8ff7763.png)

Here are my permissions and as you can see there isn't any setenforce command available:

![perm+setenf](https://user-images.githubusercontent.com/11984491/148201047-da361600-e31c-4f7c-9cca-1d131bae2835.png)
![setenf](https://user-images.githubusercontent.com/11984491/148201051-1e56620b-d2bf-4efa-8cd0-961dd3259822.png)

I've tried your SIEM on both debian 11 and ubuntu 20.04.

**Comment by amitn322** [comment]
@0xJs @benempson @vibrion121 , this issue should have been fixed. I have updated the code to use the latest Kibana, Elasticsearch and syslog-ng as well as latest alpine linux. Please let me know if you encounter any issues.

**Comment by vibrion121** [comment]
Thanks @amitn322! At this moment im not in access to the equimpent (february maybe). Thanks again for your work and commitment

**Comment by benempson** [comment]
Thanks @amitn322, I'll try this out ASAP and get back to you, will be next week at the latest.

**Comment by BosmanSander** [comment]
Thank you, @amitn322! It works perfectly now in Debian 11.
![image](https://user-images.githubusercontent.com/11984491/148749419-648c9edd-20f4-4713-8094-f583a7f78ea8.png)
